### ISSUE TITLE
Move ownership of bot to SO JS Room Org

### ISSUE THREAD

**Issue by SomeKittens** [Zirak/SO-ChatBot#191]
@ryankinal kindly created an organization for the room: https://github.com/SoJavaScriptRoom

Especially now that we've got POC code to run the bot on Node, I think it'd be good to move ownership there.  @Zirak can still be BDFL, we :heart: you!

**Comment by onebree** [comment]
I guess this isn't a thing anymore? Given that the SO-JS org no longer exists.

**Comment by Zirak** [comment]
@onebree JS org still exists, alive and kicking: https://github.com/JavaScriptRoom

I've thought this over again, and frankly I just don't feel like it. It's a project I used to work on a lot, and only a few people helped with development and maintenance. (I won't attempt to name them because I'll forget someone and he'll feel left out; this way, you're all left out equally!)

I'm not accusing anyone, nobody owes me or the bot or any collaborator anything, and I'm grateful for any help anyone can offer. But moving ownership means something and I don't feel like there's something behind it yet.

So maybe later on in our lifetimes.
