### ISSUE TITLE
Vamp Welcome Message

### ISSUE THREAD

**Issue by ndugger** [Zirak/SO-ChatBot#219]
When a new user joins the room and says their very first message, Cap spits out the welcome message.

In the room meeting, it was proposed that Cap checks their Q/A ratio, and if it's determined that they're a help vampire, we alter the message to be a little more deterrent to vamping.

We would have to come up with what an appropriate ratio is, and possible other deterrents.

**Comment by benjamingr** [comment]
+1

**Comment by MadaraUchiha** [comment]
I think it should not be just a ratio, but have a hard cap on it too (for instance, if you asked one question and provided no answers, you're not a help vamp, even though your Q:A ratio is Infinite).

Something like
```js
if (user.questions >= 10 && user.questions / user.answers > 5) { helpVamp(); }
```

Maybe even a nonlinear scale (because this current one will catch someone with 200:40 which is a (relatively?) acceptable rate.

**Comment by Zirak** [comment]
I'm not in favour for the simple reason that I don't think it'll do much good. Say Becky is a help vampire, she loooves vamping, and since the bot's greeting is customised to vamps, on entering the js room she sees something like:

> Welcome to the JavaScript room! Remember to answer question! [other crap]

And suddenly...she's a different person. "By jolly gee, that Caprica person is right!", Becky exclaims, and rushes off to answer questions.

Except that's not gonna happen. Besides telling people that they this chat's different (don't just ping people, don't ask to ask, etc), the greeting can't achieve enlightenment.

**Comment by Zirak** [comment]
Closed due to possible loss of interest. If you still want this, feel free to comment and I'll re-open.
