### ISSUE TITLE
Don't expose !!die

### ISSUE THREAD

**Issue by Unihedro** [Zirak/SO-ChatBot#227]
[I killed the bot with the `!!die` command with my bot](http://chat.stackoverflow.com/transcript/message/21772475#21772475) thinking the command would get her out of the room. It didn't happen, instead died.

Please restrict the use of `!!die` so users like I can't (accidentally, I swear) kill the bot.

**Comment by Ralt** [comment]
Maybe move up to 3 people? It's a voluntary feature for when no room owner is around and the not went mad.

**Comment by Vincentyification** [comment]
Moving it up to three sounds like a good idea.

**Comment by rlemon** [comment]
says the guy with four accounts. I vote for five users.

**Comment by SomeKittens** [comment]
`!!die` should only be exposed to room owners.

**Comment by MadaraUchiha** [comment]
How about this, if a room owner spoke within the last X minutes, !!die is not available to mortals. If they haven't, current behavior is just fine.

**Comment by SomeKittens** [comment]
Can `!!die` be room-specific?

**Comment by Vincentyification** [comment]
I +50 that idea.

**Comment by Jhawins** [comment]
I propose that [`CommunityCommand`](https://github.com/Zirak/SO-ChatBot/blob/c503d1740b024148ad94a6a56c6573dde319f6d2/source/bot.js#L401) be updated to also send `room_id` with `user_id` to `register` and ignore all community commands coming from the sandbox.

**Comment by Zirak** [comment]
> `!!die` should only be exposed to room owners. ~ @SomeKittens

Commands like `/die` are intentionally triggerable given enough "regular" user input. It's for cases where the bot bugs out and spams or is misused and there's no room owner around to stop it or it just doesn't happen. Making it owner only defeats that purpose (unless you question the purpose, which is of course cool too, but a different issue).

> Maybe move up to 3 people? ~ @Ralt 

Whether 2 is enough? Sure, I guess it can be three, to prevent the very specific case of one guy and his bot.

> Can !!die be room-specific? ~ @SomeKittens 

Making it room specific is interesting, but in the case where you want to shut the bot up in a specific room, there's `/unsummon`.

>  [...] ignore all community commands coming from the sandbox. @Jhawins 

On the one hand I see where you're coming from as we've seen lots of trolling (`/armageddon`) on sandbox, but on the other `/die` and friends seem as legitimate in Sandbox as they are in any other room.

Do note that `/die` is the most hackiest of hacks. It doesn't actually stop processing: It's more like `/shutUp`. It still executes commands, just doesn't give any output. Why? Because then `/live` would have to be special cased, and I was lazy. Teehee.

**Comment by MadaraUchiha** [comment]
TBF it's pretty rare when there are no ROs active in room 17. We cover pretty much all of the timezones methinks.

**Comment by rlemon** [comment]
How about when cap "dies" she broadcasts it to every room that didn't
invoke it.. At least then others know and can act accordingly.

**Comment by Zirak** [comment]
@rlemon A bit spammy.

@MadaraUchiha I still like having a failsafe.

**Comment by Zirak** [comment]
Closing, comment if you still think it's a good idea and I'll re-open.
