### ISSUE TITLE
Karma system

### ISSUE THREAD

**Issue by ralt** [Zirak/SO-ChatBot#231]
Doing `@Zirak++` would add one point to @Zirak's karma.

It's a simple system often used on irc. People would get karma when they're helpful, and it *could* add some incentive for people to help. It's mostly useless though, and abuse (i.e. someone spamming `@ImATroll++` in sandbox) wouldn't matter.

But it's pretty fun.

Thoughts?

**Comment by Ralt** [comment]
This might remind you of #34, but this one is only about the karma system. Nothing more.

**Comment by MadaraUchiha** [comment]
Eh, I don't know if we need *more* distractions. We already have plenty of those.

**Comment by Ralt** [comment]
I'd like to thank people without having to go on main to upvote some random answer tbh.

**Comment by darkyen** [comment]
I am neutral on this.

**Comment by allquixotic** [comment]
+1

**Comment by Shmiddty** [comment]
I'm fairly certain we had this at one point, but ended up removing it to free up localStorage.

**Comment by ssube** [comment]
This can be entertaining after a lot of input, but seems like it usually just becomes which owner/mod can get the highest score and not much else.

**Comment by rlemon** [comment]
we did have this once upon a time, and yes it was removed but not for space, iirc it was removed because it was never used appropriately (people would just spam crap). 

If we can somehow control illegitimate votes than I would be all for this.  

DO I see a real value in it? no, not really.   

Would it be neat to re-implement? sure, why not.

**Comment by Retsam** [comment]
I agree with what some others have said where I think it's only worth implementing if the abuse can be controlled.  It's only an interesting metric if it means something, and it only means something if it can't just be "maxed" with a dummy account in the sandbox.

One fix to that might be to make karma room specific, i.e. you could increase your sandbox karma all you like, but that wouldn't affect your karma in the JS room; that way someone would have to spam the JS room to increase their JS karma illegitimately, which would be pretty easy to catch.

**Comment by benjamingr** [comment]
We had this for a while and it was bad the first time. What makes you think this time will be different?

**Comment by allquixotic** [comment]
This wouldn't be abused in the Root Access room because our bot (ChatBotJohnCavil) is immune to summons and only exists in the Root Access room. There are enough room owners and moderators around that anyone trying to spam up their karma would be kicked or muted pretty quickly. 

Other than that, it would be a silly little gimmick feature with little to no point, but people like it when you gamify things, so maybe it'll get people to help out more in chat (who knows; maybe it'll do the opposite, but we've never tried it in our channel before).

My recommendations for the implementation include:

 - Only allow any given account to give karma to another specific account once every 12 hours.
 - Don't allow someone to give karma to themselves.
 - Make the karma room-specific. Not relevant to the Root Access bot, but seems to matter for the JS bot.
 - Allow room owners and mods (basically the OWNER permission group) to reset a user's karma to 0.
 - Allow room owners and mods to prevent a user from ever receiving karma again (say, set it to -1, then check if it's -1 and ignore the request if so).
 - Note that we don't need to add a system to prevent a user from giving others karma. If someone is `++`ing *everyone* and being annoying, you simply put them in mindjail, which locks them out of *all* bot commands.

A brief command API layout would look something like this:

 - `!!karmaban name-or-id` - ban a user from receiving karma by name or ID (set the karma to -1).
 - `@Username++` - give karma to a user that the bot has seen before. If the user isn't in the bot's seen list, display an error.
 - `!!karmazero name-or-id` -- set a user's karma to 0.
 - `!!karmaboard` -- display the top 10 highest karma scores in descending order with the user's display name.
 - `!!karmashow name-or-id` -- print a user's current karma value (0 if they've never received karma).

Example outputs:

Happy path:
 - `@Buddy++` ==> `Buddy's karma is now 12.` *(this prevents people from having to follow up immediately with a `!!karmashow` on `Buddy` to see where they are now.)*
 - `!!karmashow Buddy` ==> `Buddy's karma is 12.`
 - `!!karmazero Buddy` ==> `Buddy's karma is now 0.`
 - `!!karmaban Buddy` ==> `Buddy can no longer receive karma.`
 - `!!karmaunban Buddy` ==> `Buddy can now receive karma again.`
 - `!!karmaboard` (ignore any arguments) ==>

```
    Karma Leaderboard
    -------------------------
    1. JourneymanGeek ==> 9001
    2. Bob ==> 7556
    3. allquixotic ==> 1490
    4. ThatBrazilianGuy ==> 703
    5. Psycogeek ==> 655
    6. HackToHell ==> 415
    7. jokerdino ==> 392
    8. Mokubai ==> 367
    9. OliverSalzburg ==> 355
    10. CanadianLuke ==> 284
```

Failure cases:
 - (where the user sending the request has given this user karma in the past 12h): `@Buddy++` ==> `You have already given Buddy karma recently; try again later.`
 - (where `Idiot` is karmabanned): `@Idiot++` ==> bot doesn't respond; not worth the response
 - (where `Idiot` is already karmabanned): `!!karmaban Idiot` ==> bot doesn't respond; not worth the response
 - (where `Idiot` is not karmabanned): `!!karmaunban Idiot` ==> bot doesn't respond
 - (where `Idiot` is karmabanned): `!!karmazero Idiot` ==> bot doesn't respond
 - (where `Idiot` is karmabanned): `!!karmashow Idiot` ==> `Idiot is unable to receive karma.`

**Comment by SomeKittens** [comment]
I seem to recall that `c` was the leader last time we tried it, for reasons that were only obvious post-hoc.

**Comment by oliversalzburg** [comment]
Why would you postincrement when you can preincrement???

**Comment by awalGarg** [comment]
@FlorianMargaine I recommend instead to let the bot automatically increment someone's karma when someone thanks them (various ways to detect this, but ofcourse as error prone as the present idea, if not less), and only the karmashow command be exposed.

**Comment by Retsam** [comment]
@awalGarg Problem with that:

"Me: Thanks for nothing, @man"
"Bot: @man 's karma has increased by 1"
"Me: \*facepalm*"

**Comment by awalGarg** [comment]
@Retsam I agree, but as I said, "as error prone as the present idea, if not less". With the present version too, a user can give another user lots of karma (unless some serious time limits are put which will bring thier own problems). The odds of someone saying "thanks for nothing" are less than that of "thanks, TIL" etc.

Also, I don't think the bot should say that every time :)

**Comment by SomeKittens** [comment]
A better way would be to bring back the star leaderboard.

**Comment by CS1000** [comment]
What if... Star Leaderboard + Karma  

Some thoughts:  

 - It shoud be room specific  
 - with a single `!!karma` command '[@user, /Top\d/, stats]`  
 - automatically register a new user on a `@SomeKittens++`  
 - have a timer on last karma received and increment only if 3 minutes pass (one can only get so much karma/second)  
 - aaaand MEAN NOTHING !! because it just doesn't

There are ways to handle abusers, or you can just let nature run it's course.

**Comment by Zirak** [comment]
This is something that I've thought about several times but reality always ruins. The only place where I've seen it used correctly is `#xkcd` on foonetic, and IIRC it was removed there as well.

It just brings too little value and actually isn't that much fun. As after some time regulars know each other and their demeanour, having a karma system is pretty pointless. New users won't know about it, and even if they did, how would it benefit them?

Closing due to my disagreement and lack of interest. Feel free to comment if you want to keep this.
