### ISSUE TITLE
How to ask SO-ChatBot to retrieve specific questions?

### ISSUE THREAD

**Issue by kwokandy** [Zirak/SO-ChatBot#281]
Hi,

I've just called the bot in [our room](http://chat.stackoverflow.com/rooms/11391/sql). I would like to program it to be able to retrieve interesting questions from SO, for the users. But how can I do it?

Thanks

**Comment by rlemon** [comment]
That isn't within the scope of SO Chatbot. There are other bots which parse the main site (example: https://github.com/charcoal-se/smokedetector) which are more suitable for this type of thing. Zirak can chime in and re-open if he feels this is something that would be beneficial for this project.

**Comment by Zirak** [comment]
Oh hi, sorry for missing this issue!
This actually used to be a part of the bot, sort of. [It was called `/get`](https://github.com/Zirak/SO-ChatBot/blob/5b3d984d86b7c680d0b44dbae76f01f52c70790d/source/plugins/get.js), was removed some time ago because nobody besides me used it.

It mostly went around and used the [SE API](https://api.stackexchange.com/docs).
